"""add_lyrics_provenance_fields

Revision ID: 539639794bf8
Revises: 8af3d2a30b9b
Create Date: 2025-11-16 10:28:14.022376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539639794bf8'
down_revision: Union[str, Sequence[str], None] = '8af3d2a30b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_assets', sa.Column('lyrics_source', sa.String(), nullable=True))
    op.add_column('track_assets', sa.Column('lyrics_confidence', sa.Float(), nullable=True))
    op.add_column('track_assets', sa.Column('lyrics_language', sa.String(), nullable=True))
    op.add_column('track_assets', sa.Column('lyrics_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_assets', 'lyrics_metadata')
    op.drop_column('track_assets', 'lyrics_language')
    op.drop_column('track_assets', 'lyrics_confidence')
    op.drop_column('track_assets', 'lyrics_source')
    # ### end Alembic commands ###
