"""add_extra_data_to_daily_digest

Revision ID: 7c9a6cef9059
Revises: 297a635088b0
Create Date: 2025-11-19 15:21:14.539468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c9a6cef9059'
down_revision: Union[str, Sequence[str], None] = '297a635088b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_digest', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_digest_date'), table_name='daily_digest')
    op.create_index('idx_digest_date', 'daily_digest', ['digest_date'], unique=False, postgresql_ops={'digest_date': 'DESC'})
    op.drop_index(op.f('idx_release_date'), table_name='new_releases')
    op.create_index('idx_release_date', 'new_releases', ['release_date'], unique=False, postgresql_ops={'release_date': 'DESC'})
    op.drop_index(op.f('idx_detected_at'), table_name='trend_clusters')
    op.create_index('idx_detected_at', 'trend_clusters', ['detected_at'], unique=False, postgresql_ops={'detected_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_detected_at', table_name='trend_clusters', postgresql_ops={'detected_at': 'DESC'})
    op.create_index(op.f('idx_detected_at'), 'trend_clusters', [sa.literal_column('detected_at DESC')], unique=False)
    op.drop_index('idx_release_date', table_name='new_releases', postgresql_ops={'release_date': 'DESC'})
    op.create_index(op.f('idx_release_date'), 'new_releases', [sa.literal_column('release_date DESC')], unique=False)
    op.drop_index('idx_digest_date', table_name='daily_digest', postgresql_ops={'digest_date': 'DESC'})
    op.create_index(op.f('idx_digest_date'), 'daily_digest', [sa.literal_column('digest_date DESC')], unique=False)
    op.drop_column('daily_digest', 'extra_data')
    # ### end Alembic commands ###
