"""add_competitive_feature_models

Revision ID: f33fc2e17967
Revises: 46c90ae0ff06
Create Date: 2025-11-02 22:37:11.823043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33fc2e17967'
down_revision: Union[str, Sequence[str], None] = '46c90ae0ff06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.Column('avg_tunescore', sa.Float(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborator_profiles_id'), 'collaborator_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_collaborator_profiles_name'), 'collaborator_profiles', ['name'], unique=True)
    op.create_table('artist_catalog_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('valuation_multiple', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('revenue_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_catalog_valuations_artist_id'), 'artist_catalog_valuations', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_catalog_valuations_id'), 'artist_catalog_valuations', ['id'], unique=False)
    op.create_index(op.f('ix_artist_catalog_valuations_valuation_date'), 'artist_catalog_valuations', ['valuation_date'], unique=False)
    op.create_table('artist_metrics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('velocity_7d', sa.Float(), nullable=True),
    sa.Column('velocity_28d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'platform', 'snapshot_date', name='uq_artist_platform_date')
    )
    op.create_index('idx_artist_platform_date', 'artist_metrics_snapshots', ['artist_id', 'platform', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_artist_metrics_snapshots_artist_id'), 'artist_metrics_snapshots', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_metrics_snapshots_id'), 'artist_metrics_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_artist_metrics_snapshots_platform'), 'artist_metrics_snapshots', ['platform'], unique=False)
    op.create_index(op.f('ix_artist_metrics_snapshots_snapshot_date'), 'artist_metrics_snapshots', ['snapshot_date'], unique=False)
    op.create_table('breakout_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('breakout_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('predicted_7d_streams', sa.Integer(), nullable=True),
    sa.Column('predicted_14d_streams', sa.Integer(), nullable=True),
    sa.Column('predicted_28d_streams', sa.Integer(), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_7d_streams', sa.Integer(), nullable=True),
    sa.Column('prediction_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakout_predictions_artist_id'), 'breakout_predictions', ['artist_id'], unique=False)
    op.create_index(op.f('ix_breakout_predictions_id'), 'breakout_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_breakout_predictions_prediction_date'), 'breakout_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_breakout_predictions_track_id'), 'breakout_predictions', ['track_id'], unique=False)
    op.create_table('pitch_copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('elevator_pitch', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('sync_pitch', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_pitch_copy_id'), 'pitch_copy', ['id'], unique=False)
    op.create_table('playlist_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(length=100), nullable=False),
    sa.Column('playlist_name', sa.String(length=500), nullable=True),
    sa.Column('playlist_type', sa.String(length=50), nullable=True),
    sa.Column('playlist_followers', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_track_playlist', 'playlist_appearances', ['track_id', 'playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_appearances_id'), 'playlist_appearances', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_appearances_playlist_id'), 'playlist_appearances', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_appearances_track_id'), 'playlist_appearances', ['track_id'], unique=False)
    op.create_table('track_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('contributor_name', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('contribution_pct', sa.Float(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('pro', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_credits_contributor_name'), 'track_credits', ['contributor_name'], unique=False)
    op.create_index(op.f('ix_track_credits_id'), 'track_credits', ['id'], unique=False)
    op.create_index(op.f('ix_track_credits_track_id'), 'track_credits', ['track_id'], unique=False)
    op.create_table('track_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('moods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commercial_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sounds_like', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_track_tags_id'), 'track_tags', ['id'], unique=False)
    op.create_table('viral_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_alerts_id'), 'viral_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_viral_alerts_track_id'), 'viral_alerts', ['track_id'], unique=False)
    op.create_index(op.f('ix_viral_alerts_triggered_at'), 'viral_alerts', ['triggered_at'], unique=False)
    op.drop_index(op.f('idx_digest_date'), table_name='daily_digest')
    op.drop_index(op.f('ix_daily_digest_id'), table_name='daily_digest')
    op.drop_table('daily_digest')
    op.drop_index(op.f('idx_detected_at'), table_name='trend_clusters')
    op.drop_index(op.f('ix_trend_clusters_id'), table_name='trend_clusters')
    op.drop_table('trend_clusters')
    op.drop_index(op.f('idx_notable'), table_name='new_releases')
    op.drop_index(op.f('idx_release_date'), table_name='new_releases')
    op.drop_index(op.f('ix_new_releases_id'), table_name='new_releases')
    op.drop_table('new_releases')
    op.drop_index(op.f('idx_platform_date'), table_name='chart_snapshots')
    op.drop_index(op.f('ix_chart_snapshots_id'), table_name='chart_snapshots')
    op.drop_table('chart_snapshots')
    op.drop_index(op.f('ix_gear_releases_id'), table_name='gear_releases')
    op.drop_table('gear_releases')
    op.drop_index(op.f('idx_category_published'), table_name='industry_news')
    op.drop_index(op.f('idx_source_published'), table_name='industry_news')
    op.drop_index(op.f('ix_industry_news_id'), table_name='industry_news')
    op.drop_table('industry_news')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('impact_score', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('industry_news_pkey')),
    sa.UniqueConstraint('url', name=op.f('industry_news_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_industry_news_id'), 'industry_news', ['id'], unique=False)
    op.create_index(op.f('idx_source_published'), 'industry_news', ['source', 'published_at'], unique=False)
    op.create_index(op.f('idx_category_published'), 'industry_news', ['category', 'published_at'], unique=False)
    op.create_table('gear_releases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gear_releases_pkey'))
    )
    op.create_index(op.f('ix_gear_releases_id'), 'gear_releases', ['id'], unique=False)
    op.create_table('chart_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('chart_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('track_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('streams', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('movement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spotify_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chart_snapshots_pkey')),
    sa.UniqueConstraint('platform', 'chart_type', 'position', 'snapshot_date', name=op.f('chart_snapshots_platform_chart_type_position_snapshot_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_chart_snapshots_id'), 'chart_snapshots', ['id'], unique=False)
    op.create_index(op.f('idx_platform_date'), 'chart_snapshots', ['platform', 'snapshot_date'], unique=False)
    op.create_table('new_releases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('album_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('spotify_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apple_music_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('first_day_streams', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('new_releases_pkey')),
    sa.UniqueConstraint('spotify_id', name=op.f('new_releases_spotify_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_new_releases_id'), 'new_releases', ['id'], unique=False)
    op.create_index(op.f('idx_release_date'), 'new_releases', [sa.literal_column('release_date DESC')], unique=False)
    op.create_index(op.f('idx_notable'), 'new_releases', ['notable'], unique=False)
    op.create_table('trend_clusters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trend_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('example_tracks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strength_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trend_clusters_pkey'))
    )
    op.create_index(op.f('ix_trend_clusters_id'), 'trend_clusters', ['id'], unique=False)
    op.create_index(op.f('idx_detected_at'), 'trend_clusters', [sa.literal_column('detected_at DESC')], unique=False)
    op.create_table('daily_digest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('digest_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_highlights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_digest_pkey')),
    sa.UniqueConstraint('digest_date', name=op.f('daily_digest_digest_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_daily_digest_id'), 'daily_digest', ['id'], unique=False)
    op.create_index(op.f('idx_digest_date'), 'daily_digest', [sa.literal_column('digest_date DESC')], unique=False)
    op.drop_index(op.f('ix_viral_alerts_triggered_at'), table_name='viral_alerts')
    op.drop_index(op.f('ix_viral_alerts_track_id'), table_name='viral_alerts')
    op.drop_index(op.f('ix_viral_alerts_id'), table_name='viral_alerts')
    op.drop_table('viral_alerts')
    op.drop_index(op.f('ix_track_tags_id'), table_name='track_tags')
    op.drop_table('track_tags')
    op.drop_index(op.f('ix_track_credits_track_id'), table_name='track_credits')
    op.drop_index(op.f('ix_track_credits_id'), table_name='track_credits')
    op.drop_index(op.f('ix_track_credits_contributor_name'), table_name='track_credits')
    op.drop_table('track_credits')
    op.drop_index(op.f('ix_playlist_appearances_track_id'), table_name='playlist_appearances')
    op.drop_index(op.f('ix_playlist_appearances_playlist_id'), table_name='playlist_appearances')
    op.drop_index(op.f('ix_playlist_appearances_id'), table_name='playlist_appearances')
    op.drop_index('idx_track_playlist', table_name='playlist_appearances')
    op.drop_table('playlist_appearances')
    op.drop_index(op.f('ix_pitch_copy_id'), table_name='pitch_copy')
    op.drop_table('pitch_copy')
    op.drop_index(op.f('ix_breakout_predictions_track_id'), table_name='breakout_predictions')
    op.drop_index(op.f('ix_breakout_predictions_prediction_date'), table_name='breakout_predictions')
    op.drop_index(op.f('ix_breakout_predictions_id'), table_name='breakout_predictions')
    op.drop_index(op.f('ix_breakout_predictions_artist_id'), table_name='breakout_predictions')
    op.drop_table('breakout_predictions')
    op.drop_index(op.f('ix_artist_metrics_snapshots_snapshot_date'), table_name='artist_metrics_snapshots')
    op.drop_index(op.f('ix_artist_metrics_snapshots_platform'), table_name='artist_metrics_snapshots')
    op.drop_index(op.f('ix_artist_metrics_snapshots_id'), table_name='artist_metrics_snapshots')
    op.drop_index(op.f('ix_artist_metrics_snapshots_artist_id'), table_name='artist_metrics_snapshots')
    op.drop_index('idx_artist_platform_date', table_name='artist_metrics_snapshots')
    op.drop_table('artist_metrics_snapshots')
    op.drop_index(op.f('ix_artist_catalog_valuations_valuation_date'), table_name='artist_catalog_valuations')
    op.drop_index(op.f('ix_artist_catalog_valuations_id'), table_name='artist_catalog_valuations')
    op.drop_index(op.f('ix_artist_catalog_valuations_artist_id'), table_name='artist_catalog_valuations')
    op.drop_table('artist_catalog_valuations')
    op.drop_index(op.f('ix_collaborator_profiles_name'), table_name='collaborator_profiles')
    op.drop_index(op.f('ix_collaborator_profiles_id'), table_name='collaborator_profiles')
    op.drop_table('collaborator_profiles')
    # ### end Alembic commands ###
